{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datname" }
  ]
 },
 "panels": [
  {
   "title": "Number of active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  pg_stat_database_numbackends{datname=\"data_v\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size KB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"data_v\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users & Privileges Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_roles_connection_limit{job=\"db_exporter\"} > -2",
     "legendFormat": "{{rolname}}"
    }
   ]
  },
  {
   "title": "Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"db_exporter\"} / 3600",
     "legendFormat": "DB_exporter"
    },
    {
     "expr": "(time() - pg_stat_database_stats_reset{datname=\"data_v\"}) / 3600",
     "legendFormat": "DB"
    }
   ]
  },
  {
   "title": "Rows per Table",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{datname=\"data_v\"}",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": " I/O Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "  rate(pg_stat_database_blk_read_time{datname=\"data_v\"}[5m])",
     "legendFormat": "Read time ms/s"
    }
   ]
  },
  {
   "title": "Query processing speed (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "  rate(pg_stat_database_xact_commit{datname=\"data_v\"}[1m]) \r\n  + rate(pg_stat_database_xact_rollback{datname=\"data_v\"}[1m])"
    }
   ]
  },
  {
   "title": "Read/write operations rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"data_v\"}[5m])\r\n+ rate(pg_stat_database_tup_updated{datname=\"data_v\"}[5m])\r\n+ rate(pg_stat_database_tup_deleted{datname=\"data_v\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}